resources:
- type: type1
  state: dirty
  names:
  - test-boskos-01
  - test-boskos-02
  - test-boskos-03
- type: type2
  state: dirty
  useconfig: true
  names:
  - test-boskos-03
  - test-boskos-04
  - test-boskos-05
  - test-boskos-06
configs:
- name: type2
  needs:
    type1: 1
  config:
    type: GCPResourceConfig
    content: |
      projectconfigs:
      - type: type1
        clusters:
        - machinetype: n1-standard-2
          numnodes: 4
          version: 1.7
          zone: us-central-1f
        vms:
        - machinetype: n1-standard-4
          image: debian-9-drawfork
          zone: us-central-1f
