apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boskos-mason
  labels:
    app: boskos-mason
  namespace: test-pods
spec:
  replicas: 5  # 5 distributed janitor instances
  template:
    metadata:
      labels:
        app: boskos-mason
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-mason
        image: gcr.io/sebvas-experiment/mason:v20180116-f944216a4-dirty
        args:
        - --service-account=/etc/service-account/service-account.json
        - --resource-types=gce-project,gke-project,gci-qa-project,gpu-project
        - --channel-buffer-size=10
        volumeMounts:
        - mountPath: /etc/service-account
          name: service-account
          readOnly: true
      volumes:
      - name: service-account
        secret:
          secretName: boskos-service-account
